package model

// LlmComment represents a code review comment generated by the LLM.
type LlmComment struct {
	Path           string `json:"path"`
	Content        string `json:"content"`
	SuggestionCode string `json:"suggestion_code,omitempty"`
	ExistingCode   string `json:"existing_code,omitempty"`
	StartLine      int    `json:"start_line"`
	EndLine        int    `json:"end_line"`
	// SymbolID is the enclosing function's symbol-id (<relpath>::<symbol>) the
	// comment lands in, resolved from the post-change file. Lets callers key review
	// history by symbol rather than by drift-prone line numbers. Empty when the line
	// resolves to no function (or a non-Go/Python file).
	SymbolID string `json:"symbol_id,omitempty"`
	// Fingerprint is the finding's stable identity: a short hash of path+content,
	// deliberately excluding line numbers (relocation and later edits shift them).
	// Human labels (important/minor/…) and posterior evidence key on it, so a
	// re-run reproducing the same finding joins to the same label.
	Fingerprint string `json:"fingerprint,omitempty"`
	Thinking    string `json:"thinking,omitempty"`
	// Alias is the routing alias of the model that produced this comment (from
	// routing.models[].alias). Lets callers compare per-model output when a multi-model
	// pool spreads files across models (e.g. round-robin). Empty for single-model runs
	// or when no alias is configured.
	Alias string `json:"alias,omitempty"`
}

// CodeReviewResult holds raw LLM-generated review suggestion for a code segment.
type CodeReviewResult struct {
	RelevantFile      string `json:"relevant_file"`
	SuggestionContent string `json:"suggestion_content"`
	ExistingCode      string `json:"existing_code"`
	SuggestionCode    string `json:"suggestion_code"`
}
