package model

// LlmComment represents a code review comment generated by the LLM.
type LlmComment struct {
	Path           string `json:"path"`
	Content        string `json:"content"`
	SuggestionCode string `json:"suggestion_code,omitempty"`
	ExistingCode   string `json:"existing_code,omitempty"`
	StartLine      int    `json:"start_line"`
	EndLine        int    `json:"end_line"`
	// UnitID is the enclosing unit (<relpath>::<symbol>) the comment lands in,
	// resolved from the post-change file. Lets callers key review history by unit
	// rather than by drift-prone line numbers. Empty when the line resolves to no
	// function (or a non-Go/Python file).
	UnitID   string `json:"unit_id,omitempty"`
	Thinking string `json:"thinking,omitempty"`
	// Alias is the routing alias of the model that produced this comment (from
	// routing.models[].alias). Lets callers compare per-model output when a multi-model
	// pool spreads files across models (e.g. round-robin). Empty for single-model runs
	// or when no alias is configured.
	Alias string `json:"alias,omitempty"`
}

// CodeReviewResult holds raw LLM-generated review suggestion for a code segment.
type CodeReviewResult struct {
	RelevantFile      string `json:"relevant_file"`
	SuggestionContent string `json:"suggestion_content"`
	ExistingCode      string `json:"existing_code"`
	SuggestionCode    string `json:"suggestion_code"`
}
